name: log-kml
on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes (UTC)
  workflow_dispatch:
permissions:
  contents: write
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci || npm i
      - run: node logger.mjs
      - name: Commit snapshots
        run: |
          git config user.name "kml-logger[bot]"
          git config user.email "kml-logger@users.noreply.github.com"
          git add -A
          git commit -m "snapshot $(date -u +%FT%TZ)" || echo "nothing to commit"
          git push
