name: fetch-alldata
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes UTC
  workflow_dispatch:
permissions:
  contents: write
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch CSV
        run: |
          mkdir -p telemetry
          TS=$(date -u +%FT%TZ | tr ':' '-')
          curl -fsSL https://telemetry.worldsolarchallenge.org/alldata.csv -o telemetry/alldata-$TS.csv
          # keep a rolling symlink-like copy for your homepage if you want:
          cp telemetry/alldata-$TS.csv telemetry/alldata-latest.csv
      - name: Commit
        run: |
          git config user.name "telemetry-fetch[bot]"
          git config user.email "telemetry-fetch@users.noreply.github.com"
          git add -A
          git commit -m "alldata snapshot $TS" || echo "nothing to commit"
          git push